version: '3.1'

services:
  springboot:
    build: .
    # image: registry.gitlab.com/idgst/springboot-mongo-demo:latest
    restart: always
    container_name: demo-app
    ports:
      - 6060:6060
    working_dir: /opt/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: database
    ports:  # for demo/debug purpose only
      - 27017:27017
    
    restart: always
   